services:
  db:
    image: postgres:15
    container_name: dedilute_db
    restart: always
    env_file:
      - .env.${ENVIRONMENT}
    environment:
      # ให้ Postgres ใช้ค่าเดียวกับ env
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: dedilute_backend
    restart: always
    env_file:
      - .env.${ENVIRONMENT}
    ports:
      - "${BACKEND_PORT}:3000"
    depends_on:
      - db

  frontend:
    image: nginx:alpine
    container_name: dedilute_frontend
    restart: always
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend

volumes:
  postgres_data:
